activation: gelu
batch_size: 64
block_size: 256
embed_size: 384
learning_rate: 3.0e-4
lr_schedule: cosine
min_learning_rate: 0
n_layers: 6
num_heads: 6
optimizer_name: adamw
warmup_factor: 0.0
wide_factor: 4
dropout: 0.2
prenormalize: true