activation: gelu
batch_size: 64
block_size: 32
embed_size: 64
learning_rate: 3.0e-4
lr_schedule: cosine
min_learning_rate: 0
n_layers: 2
num_heads: 2
optimizer_name: adamw
prenorm: true
warmup_factor: 0.1
wide_factor: 1